# Generated by Django 5.2.3 on 2025-07-26 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_prog', 'In progression'), ('done', 'Done')], default='todo')),
                ('prior', models.CharField(choices=[('low', 'low'), ('med', 'Medium'), ('high', 'High'), ('2high', 'PIZDA HIGH')], default='low')),
                ('due', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
