# Generated by Django 5.2.3 on 2025-07-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatkas', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progression', 'In progression'), ('Done', 'Done')], default='todo'),
        ),
    ]
