# Generated by Django 5.2.3 on 2025-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatkas', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prior',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'Medium'), ('High', 'High'), ('2High', 'PIZDA HIGH')], default='low'),
        ),
    ]
